### ISSUE TITLE
Could I get a hint about the "Should return a new array, not update the original one" failure please ?

### ISSUE THREAD

**Issue by Jepassaispar** [ironhack-labs/lab-javascript-greatest-movies#961]
Could I get a hint about the "Should return a new array, not update the original one" failure please ?

_Originally posted by @Jepassaispar in https://github.com/ironhack-labs/lab-javascript-greatest-movies/pull/950#issuecomment-544477253_

**Comment by josecarneiro** [comment]
You are probably mutating the original array.

To make a shallow copy of an array, the following would suffice:

```javascript
const arrayClone = [ ...arrayOriginal ];
`
``

Closing this issue. Cheers!
